---
- name: 'Ensure LDAP auth source'
  theforeman.foreman.auth_source_ldap:
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ foreman_ldap_config['name'] }}"
    host: "{{ foreman_ldap_config['host'] }}"
    port: "{{ foreman_ldap_config['port'] | default(omit) }}"
    account: "{{ foreman_ldap_config['account'] | default(omit) }}"
    account_password: "{{ foreman_ldap_config['account_password'] | default(omit) }}"
    attr_firstname: "{{ foreman_ldap_config['attr_firstname'] | default('givenName') }}"
    attr_lastname: "{{ foreman_ldap_config['attr_lastname'] | default('sn') }}"
    attr_login: "{{ foreman_ldap_config['attr_login'] | default('uid') }}"
    attr_mail: "{{ foreman_ldap_config['attr_mail'] | default('mail') }}"
    attr_photo: "{{ foreman_ldap_config['attr_photo'] | default('jpegPhoto') }}"
    base_dn: "{{ foreman_ldap_config['base_dn'] }}"
    ca_path: "{{ foreman_ldap_config['ca_path'] | default(omit) }}"
    groups_base: "{{ foreman_ldap_config['groups_base'] | default(omit) }}"
    ldap_filter: "{{ foreman_ldap_config['ldap_filter'] | default(omit) }}"
    ldap_group_membership: "{{ foreman_ldap_config['ldap_group_membership'] | default('posix') }}"
    locations: "{{ foreman_ldap_config['locations'] | default(omit) }}"
    organizations: "{{ foreman_ldap_config['organizations'] | default(omit) }}"
    onthefly_register: "{{ foreman_ldap_config['onthefly_register'] | default(true) }}"
    server_type: "{{ foreman_ldap_config['server_type'] | default('posix') }}"
    tls: "{{ foreman_ldap_config['tls'] | default(omit) }}"
    usergroup_sync: "{{ foreman_ldap_config['usergroup_sync'] | default(true) }}"
    state: 'present'
