- name: 'Ensure DHCP settings for iPXE'
  blockinfile:
    path: '/etc/dhcp/dhcpd.hosts'
    marker: '### {mark} ANSIBLE ROLE FOREMAN MANAGED BLOCK ###'
    block: |
      if exists user-class and option user-class = "iPXE" {
        filename "http://{{ ansible_facts[foreman_instance_deploy_interface]['ipv4']['address'] }}:8000/unattended/iPXE?bootstrap=1";
      } elsif option architecture = 00:06 {
        filename "ipxe.efi";
      } elsif option architecture = 00:07 {
        filename "ipxe.efi";
      } elsif option architecture = 00:09 {
        filename "ipxe.efi";
      } else {
        filename "undionly.kpxe";
      }
  notify: 'restart dhcpd'
