---
- name: 'Ensure iPXE dependencies'
  package:
    name: 'ipxe-bootimgs'
    state: 'present'

- name: 'Ensure iPXE images in tftproot'
  copy:
    src: "/usr/share/ipxe/{{ image }}"
    dest: "/var/lib/tftpboot/{{ image }}"
    remote_src: true
    owner: 'foreman-proxy'
    group: 'root'
    seuser: 'system_u'
    serole: 'object_r'
    setype: 'cobbler_var_lib_t'
  loop:
    - 'ipxe.efi'
    - 'undionly.kpxe'
  loop_control:
    loop_var: 'image'

- name: 'Ensure DHCP settings for iPXE'
  copy:
    dest: '/etc/dhcp/dhcpd-ipxe.conf'
    content: |
      if exists user-class and option user-class = "iPXE" {
        filename "http://{{ ansible_facts[foreman_instance_deploy_interface]['ipv4']['address'] }}:8000/unattended/iPXE?bootstrap=1";
      } elsif option architecture = 00:06 {
        filename "ipxe.efi";
      } elsif option architecture = 00:07 {
        filename "ipxe.efi";
      } elsif option architecture = 00:09 {
        filename "ipxe.efi";
      } else {
        filename "undionly.kpxe";
      }
    owner: 'root'
    group: 'dhcpd'
    mode: 0444

- name: 'Configure DHCP server for iPXE'
  lineinfile:
    path: '/etc/foreman-installer/custom-hiera.yaml'
    owner: 'root'
    group: 'root'
    mode: 0444
    line: 'dhcp::includes: "/etc/dhcp/dhcpd-ipxe.conf"'
    regexp: '^dhcp::includes'
  register: 'set_dhcp_includes'

- name: 'Run foreman-installer'
  shell: |
    export LANG="en_US.UTF-8"
    export LC_ALL="en_US.UTF-8"
    /sbin/foreman-installer
  when: set_dhcp_includes['changed']
