- name: 'Create empty list'
  set_fact:
    cv_repo_list: []

- name: 'Make repo list for content views'
  set_fact:
    cv_repo_list: "{{ cv_repo_list + [{'product': item.name, 'name': item.name + '-' + repo.name } ] }}"
  loop: "{{ item.repositories }}"
  loop_control:
    loop_var: 'repo'

- name: 'Ensure base content views'
  theforeman.foreman.content_view:
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    organization: "{{ foreman_organization }}"
    name: "CV {{ item.name }}"
    repositories: "{{ cv_repo_list }}"
    state: 'present'
