---
- name: 'Prepare system for Red Hat Satellite installtion'
  block:
    - name: 'Ensure Red Hat Subscriptions'
      community.general.redhat_subscription:
        username: "{{ foreman_redhat_support_user }}"
        password: "{{ foreman_redhat_support_password }}"
        auto_attach: true
        pool: 'Red Hat Satellite'
        state: 'present'

    - name: 'Ensure Red Hat Satellite Repositories'
      community.general.rhsm_repository:
        name:
          - 'rhel-7-server-rpms'
          - 'rhel-7-server-satellite-6.10-rpms'
          - 'rhel-7-server-satellite-maintenance-6-rpms'
          - 'rhel-server-rhscl-7-rpms'
          - 'rhel-7-server-ansible-2.9-rpms'
        purge: true
        state: 'present'

    - name: 'Install Satellite packages'
      ansible.builtin.package:
        name:
          - 'satellite'
        state: 'present'
  when: not foreman_satellite_offline_install

- name: 'Install Red Hat Satellite from ISO'
  block:
    - name: 'Mount Red Hat Satellite ISO'
      ansible.posix.mount:
        src: "{{ foreman_satellite_dvd_drive }}"
        path: '/mnt/sat_iso'
        fstype: 'iso9660'
        state: 'mounted'

    - name: 'Run installer script'
      ansible.builtin.shell: |
        cd /mnt/sat_iso
        ./install_packages
  when: foreman_satellite_offline_install

- name: 'Enable Satellite firewalld service'
  ansible.posix.firewalld:
    service: 'RH-Satellite-6'
    state: 'enabled'
    permanent: true
    immediate: true

- name: 'Run Satellite installer default scenario (see /var/log/foreman-installer/satellite.log for details)'
  ansible.builtin.shell: |
    export LANG="en_US.UTF-8"
    export LC_ALL="en_US.UTF-8"
    /usr/sbin/satellite-installer --scenario satellite \
      --foreman-initial-admin-username {{ foreman_admin_user }} \
      --foreman-initial-admin-password {{ foreman_admin_password | quote }} \
      --foreman-initial-organization {{ foreman_organization }} \
      --foreman-proxy-puppetca true \
      --foreman-proxy-tftp true \
      --enable-foreman-plugin-discovery \
      --no-lock-package-versions

- name: 'End of installation notice'
  ansible.builtin.debug:
    msg: |
      NOTICE: You have installed Satellite in Offline mode, please note the following points:
        1. This system CAN NOT be registered to the Satellite Server it hosts!
        2. This system might still be unlicensed, please check https://access.redhat.com/solutions/3121571
  when: foreman_satellite_offline_install
