---
- name: 'Set firewall ports'
  ansible.posix.firewalld:
    port: "{{ port['name'] }}"
    permanent: true
    immediate: true
    state: 'enabled'
  loop:
    - name: '7/tcp'
    - name: '7/udp'
    - name: '53/tcp'
    - name: '53/udp'
    - name: '67/udp'
    - name: '69/udp'
    - name: '80/tcp'
    - name: '443/tcp'
    - name: '5000/tcp'
    - name: '5646/tcp'
    - name: '5647/tcp'
    - name: '8000/tcp'
    - name: '8140/tcp'
      enable: "{{ foreman_puppet_enabled }}"
    - name: '8443/tcp'
    - name: '9090/tcp'
  loop_control:
    loop_var: 'port'
  when: port['enable'] | default(true)

- name: 'Upgrade postgres on EL8'
  include_role:
    name: 'theforeman.operations.postgresql_upgrade'
  when: ansible_facts['distribution_major_version'] == '8'
