---
- name: 'Set firewall ports'
  ansible.posix.firewalld:
    port: "{{ port }}"
    permanent: true
    immediate: true
    state: 'enabled'
  loop:
    - '7/tcp'
    - '7/udp'
    - '53/tcp'
    - '53/udp'
    - '67/udp'
    - '69/udp'
    - '80/tcp'
    - '443/tcp'
    - '8000/tcp'
    - '5000/tcp'
    - '5646/tcp'
    - '5647/tcp'
    - '8140/tcp'
    - '8443/tcp'
    - '9090/tcp'
  loop_control:
    loop_var: 'port'

- name: 'Create SELinux module directory'
  file:
    path: '/etc/selinux/modules'
    state: 'directory'

- name: 'Copy MongoDB SELinux files'
  copy:
    dest: "/etc/selinux/modules/{{ file }}"
    src: "selinux_configs/{{ file }}"
    mode: 0600
  loop:
    - 'mongod_sock.pp'
    - 'mongod_sock.te'
  loop_control:
    loop_var: 'file'

- name: 'Load SELinux modules'
  command: "/usr/sbin/semodule -i /etc/selinux/modules/{{ module }}.pp"
  loop:
    - 'mongod_sock'
  loop_control:
    loop_var: 'module'
