---
- name: 'Gather running services'
  ansible.builtin.service_facts:

- name: 'Ensure current IP is tied to hostname in /etc/hosts for DNS resolution check'
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: "{{ ansible_facts['default_ipv4']['address'] }} {{ ansible_facts['fqdn'] }}"

- name: 'Set firewall services'
  ansible.posix.firewalld:
    service: "{{ service['name'] }}"
    permanent: true
    immediate: true
    state: 'enabled'
  loop:
    - name: 'dhcp'
    - name: 'dns'
    - name: 'http'
    - name: 'https'
    - name: 'puppetmaster'
      enable: "{{ foreman_puppet_enabled }}"
    - name: 'tftp'
  loop_control:
    loop_var: 'port'
  when:
    - service['enable'] | default(true) | bool
    - ansible_facts['services']['firewalld']['status'] is defined
    - ansible_facts['services']['firewalld']['status'] == 'enabled'

- name: 'Set firewall ports'
  ansible.posix.firewalld:
    port: "{{ port['name'] }}"
    permanent: true
    immediate: true
    state: 'enabled'
  loop:
    - name: '8000/tcp'
    - name: '9090/tcp'
  loop_control:
    loop_var: 'port'
  when:
    - port['enable'] | default(true) | bool
    - ansible_facts['services']['firewalld']['status'] is defined
    - ansible_facts['services']['firewalld']['status'] == 'enabled'
