---
- name: 'Set server_type'
  ansible.builtin.set_fact:
    foreman_server_type: 'satellite_capsule'

- name: 'Ensure Red Hat Subscriptions'
  community.general.redhat_subscription:
    username: "{{ foreman_redhat_support_user }}"
    password: "{{ foreman_redhat_support_password }}"
    auto_attach: true
    pool: 'Red Hat Satellite Capsule'
    state: 'present'

- name: 'Install dependencies'
  ansible.builtin.package:
    name:
      - 'satellite-capsule'
    state: 'present'

- name: 'Ensure Satellite Capsule module'
  ansible.builtin.command: dnf module enable -y satellite-capsule:el8
  register: module_enable
  changed_when: "'Nothing to do' not in module_enable['stdout']"

- name: 'Enable Satellite firewalld service'
  ansible.posix.firewalld:
    service: 'RH-Satellite-6'
    state: 'enabled'
    permanent: true
    immediate: true

- name: 'Enable Satellite Capsule Discovery port'
  ansible.posix.firewalld:
    port: '8443/tcp'
    state: 'enabled'
    permanent: true
    immediate: true

- name: 'Generate certificates on Satellite Server'
  ansible.builtin.shell: |
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    /usr/sbin/foreman-proxy-certs-generate \
      --no-colors \
      --foreman-proxy-fqdn "{{ ansible_facts['fqdn'] | lower }}" \
      --certs-tar /root/{{ ansible_facts['fqdn'] | lower }}.tar
  delegate_to: "{{ groups['foreman'][0] }}"
  register: 'foreman_certs_gen'
  changed_when: true

- name: 'Copy certificate tar to Ansible Controller'
  ansible.builtin.fetch:
    src: "/root/{{ ansible_facts['fqdn'] | lower }}.tar"
    dest: '/tmp/'
    flat: true
  delegate_to: "{{ groups['foreman'][0] }}"

- name: 'Copy certificate tar to Satellite Capsule'
  ansible.builtin.copy:
    src: "/tmp/{{ ansible_facts['fqdn'] | lower }}.tar"
    dest: '/root'
    mode: 0600

- name: 'Remove certificate tar from Ansible Controller'
  ansible.builtin.file:
    path: "/tmp/{{ ansible_facts['fqdn'] | lower }}.tar"
    state: 'absent'
  delegate_to: 'localhost'

- name: 'Compose foreman-installer command'
  ansible.builtin.set_fact:
    foreman_installer_cmd: "{{ foreman_certs_gen['stdout_lines'][-11:] + ['--detailed-exitcodes'] }}"

- name: 'Run foreman-installer on Proxy'
  ansible.builtin.shell: |
    set -o pipefail
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    echo {{ foreman_installer_cmd | join(' ') }} | sed 's/\\//' | bash
  register: 'installer_output'
  changed_when: installer_output['rc'] == 2
  failed_when: installer_output['rc'] == 1 or installer_output['rc'] == 4 or installer_output['rc'] == 6

- name: 'Configure Host Deployment and Discovery'
  block:
    - name: 'Configure Foreman for deployment'
      ansible.builtin.include_tasks: 'configure_deployment.yml'

    - name: 'Configure Host Discovery'
      ansible.builtin.shell: |
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        /usr/sbin/foreman-installer \
        --enable-foreman-proxy-plugin-discovery \
        --no-lock-package-versions \
        --detailed-exitcodes
      register: 'installer_output'
      changed_when: installer_output['rc'] == 2
      failed_when: installer_output['rc'] == 1 or installer_output['rc'] == 4 or installer_output['rc'] == 6

- name: 'Fix warnings by setting permissions'
  ansible.posix.acl:
    path: "{{ path }}"
    entity: 'foreman-proxy'
    etype: 'user'
    permissions: 'r'
    state: 'present'
  loop:
    - '/var/lib/pulp/content'
  loop_control:
    loop_var: 'path'

- name: 'After installation message'
  ansible.builtin.pause:
    prompt: |
      Installation succesful!
      As of this time there is no module available to configure Satellite Capsules in Ansible.
      Please log in on {{ foreman_url }} , assign it manually and sync the proxy.
      Also run a configuration run for Satellite again to update any Host Groups with the new proxy.

      Press enter to continue
