---
# Foreman/Katello versions are linked, check Katello docs for more information
- name: 'Set default input'
  set_fact:
    foreman_upgrade: false
  when: foreman_upgrade is not defined

- name: 'Set versions'
  set_fact:
    foreman_repositories_version: 2.4
    foreman_repositories_katello_version: 4.0
    foreman_installer_package: 'foreman-installer-katello'
    foreman_installer_scenario: 'katello'

- name: 'Set installer options'
  set_fact:
    foreman_installer_options:
      - "--foreman-initial-admin-password {{ foreman_admin_password | quote }}"
  when: not foreman_upgrade

- name: 'Run Katello upgrade check'
  command: foreman-rake katello:upgrade_check
  when: foreman_upgrade

- name: 'Install EPEL on EL7'
  yum:
    name: 'epel-release'
    state: 'present'
  when: ansible_facts['distribution_major_version'] == '7'

- name: 'Run common tasks'
  include_tasks: 'install_foreman_common.yml'

- name: 'Setup Foreman & Katello repositories'
  include_role:
    name: 'theforeman.operations.foreman_repositories'

- name: 'Setup Puppet repositories'
  include_role:
    name: 'theforeman.operations.puppet_repositories'

- name: 'Upgrade postgres on EL8'
  include_role:
    name: 'theforeman.operations.postgresql_upgrade'
  when: ansible_facts['distribution_major_version'] == '8'

- name: 'Clear yum cache'
  file:
    path: '/var/cache/yum'
    state: 'absent'

- name: 'Upgrade all installed packages'
  yum:
    name: '*'
    state: 'latest'
    update_cache: true
  when: foreman_upgrade

- name: 'Run Foreman/Katello installer'
  include_role:
    name: 'theforeman.operations.installer'

- name: 'Remove Pulp 2'
  shell: yes | foreman-maintain content remove-pulp2
  when: foreman_repositories_version is version ('2.4', '>=')
