---
# Foreman/Katello versions are linked, check Katello docs for more information
- name: 'Set default input'
  ansible.builtin.set_fact:
    foreman_upgrade: false
  when: foreman_upgrade is not defined

- name: 'Set versions'
  ansible.builtin.set_fact:
    foreman_repositories_version: "{{ foreman_foreman_version }}"
    foreman_repositories_katello_version: "{{ foreman_katello_version }}"
    foreman_installer_package: 'foreman-installer-katello'
    foreman_installer_scenario: 'katello'

- name: 'Set installer options'  # yamllint disable rule:line-length
  ansible.builtin.set_fact:
    foreman_installer_options:
      - "--foreman-initial-admin-password {{ foreman_admin_password | quote }}"
      - "--foreman-initial-organization {{ foreman_organization }}"
      - "--foreman-initial-location {{ foreman_locations[0] }}"
      - "{{ foreman_puppet_enabled | ternary(None, '--no-enable-puppet --foreman-proxy-puppet false --foreman-proxy-puppetca false') }}"  # noqa yaml
      - '--no-lock-package-versions'
  when: not foreman_upgrade | bool

- name: 'Set installer options for TLS certificate'
  ansible.builtin.include_tasks: 'configure_custom_tls.yml'
  vars:
    foreman_custom_webui_run_installer: false  # Only set options
  when: foreman_custom_webui_cert | length > 0

- name: 'Run Katello upgrade check'
  ansible.builtin.command: foreman-rake katello:upgrade_check
  changed_when: false
  when: foreman_upgrade | bool

- name: 'Run common tasks'
  ansible.builtin.include_tasks: 'install_foreman_common.yml'

- name: 'Setup Foreman & Katello repositories'
  ansible.builtin.include_role:
    name: 'theforeman.operations.foreman_repositories'

- name: 'Setup Puppet repositories'
  ansible.builtin.include_role:
    name: 'theforeman.operations.puppet_repositories'

- name: 'Clear yum cache'
  ansible.builtin.file:
    path: '/var/cache/yum'
    state: 'absent'

- name: 'Enable maintenance-mode'
  ansible.builtin.command: foreman-maintain maintenance-mode start
  changed_when: true
  when: foreman_upgrade | bool

- name: 'Upgrade all installed packages'  # noqa package-latest
  ansible.builtin.package:
    name: '*'
    state: 'latest'
    update_cache: true
  when: foreman_upgrade | bool

- name: 'Run Foreman/Katello installer'
  ansible.builtin.include_role:
    name: 'theforeman.operations.installer'

- name: 'Disable maintenance-mode'
  ansible.builtin.command: foreman-maintain maintenance-mode stop
  changed_when: true
  when: foreman_upgrade | bool
