---
- name: 'Set firewall ports'
  ansible.posix.firewalld:
    port: "{{ port }}"
    permanent: true
    immediate: true
    state: 'enabled'
  loop:
    - '7/tcp'
    - '7/udp'
    - '53/tcp'
    - '53/udp'
    - '67/udp'
    - '69/udp'
    - '80/tcp'
    - '443/tcp'
    - '5000/tcp'
    - '5646/tcp'
    - '5647/tcp'
    - '8000/tcp'
    - "{{ foreman_puppet_enabled | ternary('8140/tcp', None) }}"
    - '8443/tcp'
    - '9090/tcp'
  loop_control:
    loop_var: 'port'
