---
- name: 'Install Foreman server'
  hosts: 'foreman'
  vars:
    foreman_upgrade: false  # Set to true to upgrade current Foreman server
  tasks:
    - name: 'Run Foreman role'
      ansible.builtin.import_role:
        name: 'foreman'
        tasks_from: 'install_foreman.yml'

- name: 'Install Foreman Smart Proxies'
  hosts: 'foreman_proxies'
  tasks:
    - name: 'Run Foreman role'
      ansible.builtin.import_role:
        name: 'foreman'
        tasks_from: 'install_foreman_smartproxy.yml'
