---
- name: 'Install Foreman server'
  hosts: 'foreman'
  tasks:
    - name: 'Run Foreman role'
      import_role:
        name: 'foreman'
        tasks_from: 'install_foreman.yml'

- name: 'Install Foreman Smart Proxies'
  hosts: 'foreman_proxies'
  tasks:
    - name: 'Run Foreman role'
      import_role:
        name: 'foreman'
        tasks_from: 'install_foreman_smartproxy.yml'
