- name: 'Install Foreman'
  hosts: 'foreman'
  become: true
  vars:
    # Foreman/Katello versions are linked, check Katello docs for more information
    foreman_version: 2.0
    katello_version: 3.15
    foreman_initial_admin_password: "{{ foreman_admin_password }}"
  tasks:
    - name: 'Install EPEL'
      yum:
        name: 'epel-release'
        state: 'present'
    - name: 'Install supporting tools'
      yum:
        name:
          - 'git'
          - 'ansible'
        state: 'present'
        update_cache: true
    - name: 'Ensure resources directory'
      file:
        path: '/opt/resources'
        state: 'directory'
    - name: 'Set up Forklift'
      git:
        repo: 'https://github.com/theforeman/forklift.git'
        dest: '/opt/resources/forklift'
    - name: 'Set firewall ports'
      firewalld:
        port: "{{ port }}"
        permanent: true
        immediate: true
        state: 'enabled'
      loop:
        - '7/tcp'
        - '7/udp'
        - '53/tcp'
        - '53/udp'
        - '67/udp'
        - '69/udp'
        - '80/tcp'
        - '443/tcp'
        - '8000/tcp'
        - '8140/tcp'
        - '9090/tcp'
      loop_control:
        loop_var: 'port'
    - name: 'Create SELinux module directory'
      file:
        path: '/etc/selinux/modules'
        state: 'directory'

    - name: 'Copy MongoDB SELinux files'
      copy:
        dest: "/etc/selinux/modules/{{ file }}"
        src: "selinux_configs/modules/{{ file }}"
      loop:
        - 'mongod_sock.pp'
        - 'mongod_sock.te'
      loop_control:
        loop_var: 'file'

    - name: 'Load SELinux modules'
      command: "/usr/sbin/semodule -i /etc/selinux/modules/{{ module }}.pp"
      loop:
        - 'mongod_sock'
      loop_control:
        loop_var: 'module'

    - name: 'Run Ansible on remote host (see /var/log/foreman_install_ansible.log for details)'
      shell: |
        export ANSIBLE_LOG_PATH=/var/log/foreman_install_ansible.log
        export LANG="en_US.UTF-8"
        export LC_ALL="en_US.UTF-8"
        cd /opt/resources/forklift
        ansible-playbook -i localhost, -c local \
        /opt/resources/forklift/playbooks/katello.yml \
        -e foreman_repositories_version={{ foreman_version }} \
        -e katello_repositories_version={{ katello_version }} \
        -e foreman_installer_admin_password={{ foreman_initial_admin_password }}
      no_log: "{{ not foreman_debug }}"
