---
- name: 'Install Satellite Server'
  hosts: 'foreman'
  become: true
  tasks:
    - name: 'Ensure Red Hat Subscriptions'
      community.general.redhat_subscription:
        state: 'present'
        username: "{{ foreman_redhat_support_user }}"
        password: "{{ foreman_redhat_support_password }}"
        auto_attach: true
        pool: '^(Red Hat Enterprise Server|Red Hat Satellite Infrastructure Subscription)$'
      when: not foreman_satellite_offline_install

    - name: 'Ensure Red Hat Satellite Repositories'
      community.general.rhsm_repository:
        state: 'present'
        name:
          - 'rhel-7-server-rpms'
          - 'rhel-7-server-satellite-6.6-rpms'
          - 'rhel-7-server-satellite-maintenance-6-rpms'
          - 'rhel-server-rhscl-7-rpms'
          - 'rhel-7-server-ansible-2.8-rpms'
        purge: true
      when: not foreman_satellite_offline_install

    - name: 'Install Satellite packages'
      package:
        name:
          - 'satellite'
          - 'python27-python-pip'
        state: 'present'

    - name: 'Place wrapper scripts for PiP'
      copy:
        dest: '/usr/local/bin/ansible_foreman_pip'
        mode: 0755
        content: |
          #!/bin/bash
          # This file is part of Ansible Foreman
          . /opt/rh/python27/enable
          exec pip "$@"

    - name: 'Place wrapper scripts for Python'
      copy:
        dest: '/usr/local/bin/ansible_foreman_python'
        mode: 0755
        content: |
          #!/bin/bash
          # This file is part of Ansible Foreman
          . /opt/rh/python27/enable
          exec python "$@"

    - name: 'Run Satellite installer default scenario (see /var/log/foreman-installer/satellite.log for details)'
      shell: |
        export LANG="en_US.UTF-8"
        export LC_ALL="en_US.UTF-8"
        satellite-installer --scenario satellite \
          --foreman-initial-admin-username {{ foreman_admin_user }} \
          --foreman-initial-admin-password {{ foreman_admin_password }} \
          --foreman-proxy-puppetca true \
          --foreman-proxy-tftp true \
          --enable-foreman-plugin-discovery
